name: 'jaffle_shop'

config-version: 2
version: '0.1'

profile: 'jaffle_shop'

# https://docs.getdbt.com/reference/project-configs/quoting
quoting:
  database: true
  schema: true
  identifier: true

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

#tests:
#  jaffle_shop: #https://docs.getdbt.com/reference/test-configs#general-configurations
#    +store_failures: true  # all tests
#    +database: KEBOOLA_7167
#    +schema: WORKSPACE_19288457

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  jaffle_shop:
      materialized: table
      staging:
        materialized: table
