version: 2

sources:
  - name: WORKSPACE_19288457
    freshness: # default freshness
      warn_after: {count: 7, period: day}
      error_after: {count: 30, period: day}
    loaded_at_field: "_timestamp"

    quoting:
      database: true
      schema: true
      identifier: true

    tables:
      - name: raw_customers
        description: "Extracted list of customers"
        identifier: "raw_customers"
        tags: ["ecommerce", "crm"]
#        columns:
 #         - name: '"id"'
#$            tests:
#              - unique
#              - not_null

      - name: raw_orders
        description: "Extracted list of orders"
        identifier: "raw_orders"
        tags: ["ecommerce"]

      - name: raw_payments
        description: "Extracted list of payments"
        identifier: "raw_payments"
        tags: ["ecommerce"]