version: 2

sources:
  - name: WORKSPACE_19288457
    freshness: # default freshness
      warn_after: {count: 7, period: day}
      error_after: {count: 30, period: day}
    loaded_at_field: "_timestamp"

    tables:
      - name: raw_customers
        description: "Extracted list of customers"
#        meta: {<dictionary>}
        identifier: "raw_customers"
#        tests:
#          - <test>
#          - ... # declare additional tests
        tags: ["ecommerce", "crm"]

        quoting:
          database: true
          schema: true
          identifier: true
#        columns:
 #         - name: '"id"'
#$            tests:
#              - unique
#              - not_null

      - name: raw_orders
        description: "Extracted list of orders"
#        meta: {<dictionary>}
        identifier: "raw_orders"
#        tests:
#          - <test>
#          - ... # declare additional tests
        tags: ["ecommerce"]

        quoting:
          database: true
          schema: true
          identifier: true

      - name: raw_payments
        description: "Extracted list of payments"
#        meta: {<dictionary>}
        identifier: "raw_payments"
#        tests:
#          - <test>
#          - ... # declare additional tests
        tags: ["ecommerce"]

        quoting:
          database: true
          schema: true
          identifier: true